sequenceDiagram
    title: Diagram just to illustrate link between LikeC4 and Mermaid diagrams    participant Alice

    participant John

    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!

    link Alice: Dashboard @ https://dashboard.contoso.com/alice
